// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import {FHE, euint64, ebool, externalEuint64} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";

contract DVPN is ZamaEthereumConfig {
    struct Session {
        euint64 encryptedStartTime;
        address nodeProvider;
        uint256 hardTimeoutLimit;
        bool isActive;
    }

    // Mapping from user address => their active session
    mapping(address => Session) internal activeSessions;

    // Mapping from provider address => their accumulated encrypted earnings
    mapping(address => euint64) public providerBalances;

    // Price per second of usage (plaintext multiplier for computation convenience)
    uint64 public ratePerSecond;
    
    // Trusted relayer that submits transactions on behalf of Flow users
    address public trustedRelayer;

    event SessionStarted(address indexed user, address indexed provider);
    event SessionEnded(address indexed user, address indexed provider, bool timedOut);

    constructor(uint64 _ratePerSecond, address _trustedRelayer) {
        require(_trustedRelayer != address(0), "Invalid relayer");
        ratePerSecond = _ratePerSecond;
        trustedRelayer = _trustedRelayer;
    }

    /// @notice Initialize a new dVPN session
    /// @dev User passes their encrypted timestamp `externalEuint64` generated by Zama SDK on the frontend.
    function startSession(address _user, address _nodeProvider, externalEuint64 inputStartTime, bytes calldata inputProof) external {
        require(_user != address(0), "Invalid user");
        require(_nodeProvider != address(0), "Invalid provider");
        require(msg.sender == _user || msg.sender == trustedRelayer, "Unauthorized to start session");
        require(!activeSessions[_user].isActive, "Session already active");

        // Validate encrypted input and import ciphertext handle.
        euint64 startTime = FHE.fromExternal(inputStartTime, inputProof);
        FHE.allowThis(startTime);

        // Save the session.
        activeSessions[_user] = Session({
            encryptedStartTime: startTime,
            nodeProvider: _nodeProvider,
            hardTimeoutLimit: block.timestamp + 24 hours,
            isActive: true
        });

        // Initialize provider balance when first seen.
        if (!FHE.isInitialized(providerBalances[_nodeProvider])) {
            providerBalances[_nodeProvider] = FHE.asEuint64(0);
        }
        FHE.allowThis(providerBalances[_nodeProvider]);
        FHE.allow(providerBalances[_nodeProvider], _nodeProvider);

        emit SessionStarted(_user, _nodeProvider);
    }

    /// @notice Ends an active dVPN session, computing duration and updating provider balance
    /// @dev Can be called by the user OR the node provider (Dual-termination).
   function endConfidentialSession(address _user, externalEuint64 inputEndTime, bytes calldata inputProof) external {
    Session storage session = activeSessions[_user];
    require(session.isActive, "No active session");
    require(msg.sender == _user || msg.sender == session.nodeProvider || msg.sender == trustedRelayer, "Unauthorized");

    euint64 endTime = FHE.fromExternal(inputEndTime, inputProof);

    // SECURITY FIX: If endTime < startTime, set duration to 0 instead of reverting
    // (we cannot revert based on encrypted values — use FHE.select instead)
    ebool isValid = FHE.ge(endTime, session.encryptedStartTime);

    euint64 rawDuration = FHE.sub(endTime, session.encryptedStartTime);

    // If invalid (endTime < startTime), duration becomes 0 → payment becomes 0
    euint64 duration = FHE.select(isValid, rawDuration, FHE.asEuint64(0));

    // Compute payment: duration * ratePerSecond
    euint64 payment = FHE.mul(duration, FHE.asEuint64(ratePerSecond));

    // Add payment to provider's encrypted balance
    providerBalances[session.nodeProvider] = FHE.add(providerBalances[session.nodeProvider], payment);

    FHE.allowThis(providerBalances[session.nodeProvider]);
    FHE.allow(providerBalances[session.nodeProvider], session.nodeProvider);

    session.isActive = false;

    emit SessionEnded(_user, session.nodeProvider, false);
}

    /// @notice Failsafe timeout resolver (can be called by anyone to clear hanging sessions)
    function resolveTimeoutSession(address _user) external {
        Session storage session = activeSessions[_user];
        require(session.isActive, "No active session");
        require(block.timestamp > session.hardTimeoutLimit, "Timeout limit not reached");

        // For now, we just forcefully clear without updating balance.
        session.isActive = false;
        
        emit SessionEnded(_user, session.nodeProvider, true);
    }

}
