import { ethers } from "ethers";
import { logger } from "./logger";
import DVPN from "./DVPN.json";

// In production, these should be set in .env
const RPC_URL = process.env.ZAMA_RPC_URL || "https://rpc.sepolia.org"; // Using public sepolia here for demo
// DO NOT use hardcoded private keys in production! This is just the Hardhat default account #0 for testing
const RELAYER_PRIVATE_KEY = process.env.RELAYER_PRIVATE_KEY || "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"; 
const CONTRACT_ADDRESS = process.env.DVPN_CONTRACT_ADDRESS || "0x00000000000000000000000000000000DVPNMOCK";

let provider: ethers.Provider;
let relayerWallet: ethers.Wallet;
let dvpnContract: ethers.Contract;

export const initRelayer = () => {
  if (provider) return;
  
  try {
    provider = new ethers.JsonRpcProvider(RPC_URL);
    relayerWallet = new ethers.Wallet(RELAYER_PRIVATE_KEY, provider);
    dvpnContract = new ethers.Contract(CONTRACT_ADDRESS, DVPN.abi, relayerWallet);
    logger.info({ address: relayerWallet.address }, "Zama Trusted Relayer Initialized");
  } catch (err) {
    logger.error({ err }, "Failed to initialize Zama Trusted Relayer");
  }
};

/**
 * Acts as the trusted relayer to start a session on the Zama fhEVM network.
 * Allows the user to authenticate via their Flow Passkey while the backend pays the Sepolia/Zama gas.
 */
export const startSessionOnChain = async (
  userAddress: string,
  nodeProviderProxy: string,
  encryptedPayloadStr: string
): Promise<string> => {
  initRelayer();
  
  try {
    // Parse the payload generated by fhevmjs
    const payload = JSON.parse(encryptedPayloadStr);
    const { handle, inputProof } = payload;
    
    logger.info({ userAddress, nodeProviderProxy }, "Relaying startSession to Zama fhEVM...");
    
    // In a real env, this executes the transaction
    if (CONTRACT_ADDRESS === "0x00000000000000000000000000000000DVPNMOCK") {
      logger.info("Mock Contract interaction. Simulating transaction success.");
      return "0xMOCK_TX_HASH_START";
    }

    const tx = await dvpnContract.startSession(userAddress, nodeProviderProxy, handle, inputProof);
    await tx.wait();
    
    return tx.hash;
  } catch (err: any) {
    logger.error({ err, userAddress }, "FHE Relayer: Failed to start session on-chain");
    throw new Error(`Zama Relayer Error: ${err.message}`);
  }
};

/**
 * Acts as the trusted relayer to end a session on the Zama fhEVM network.
 * The contract homomorphically calculates duration and payment values blindly.
 */
export const endSessionOnChain = async (
  userAddress: string,
  encryptedPayloadStr: string
): Promise<string> => {
  initRelayer();
  
  try {
    // Parse the payload generated by fhevmjs
    const payload = JSON.parse(encryptedPayloadStr);
    const { handle, inputProof } = payload;
    
    logger.info({ userAddress }, "Relaying endConfidentialSession to Zama fhEVM...");
    
    // In a real env, this executes the transaction
    if (CONTRACT_ADDRESS === "0x00000000000000000000000000000000DVPNMOCK") {
      logger.info("Mock Contract interaction. Simulating transaction success.");
      return "0xMOCK_TX_HASH_END";
    }

    const tx = await dvpnContract.endConfidentialSession(userAddress, handle, inputProof);
    await tx.wait();
    
    return tx.hash;
  } catch (err: any) {
    logger.error({ err, userAddress }, "FHE Relayer: Failed to end session on-chain");
    throw new Error(`Zama Relayer Error: ${err.message}`);
  }
};
